name: TNTRun
version: '${project.version}'
main: io.github.cardsandhuskers.tntrun.TNTRun
api-version: 1.19
depend: [ PlaceholderAPI, Teams ]
softdepend: [Multiverse-Core]
authors: [ cardsanduskers ]
description: tnt run
commands:
  saveRunArena:
    description: save arena data so that it can be rebuilt
    command: /<command>
  setRunPos1:
    description: set corner 1 of arena
    command: /<command>
  setRunPos2:
    description: set corner 1 of arena
    command: /<command>
  startTNTRun:
    description: start the game
    command: /<command> [multiplier]
  setRunSpawn:
    description: set spawnpoint
    command: /<command>
  setLobby:
    description: sets the location of the lobby
    command: /<command>