name: TNTRun
version: '${project.version}'
main: io.github.cardsandhuskers.tntrun.TNTRun
api-version: 1.19
depend: [PlaceholderAPI, Teams, FastAsyncWorldEdit]
authors: [ cardsanduskers ]
description: tnt run
commands:
  saveTNTRunArena:
    description: save arena data so that it can be rebuilt
    command: /<command>
  setTNTRunPos1:
    description: set corner 1 of arena
    command: /<command>
  setTNTRunPos2:
    description: set corner 1 of arena
    command: /<command>
  startTNTRun:
    description: start the game
    command: /<command> [multiplier]
  setTNTRunSpawn:
    description: set spawnpoint
    command: /<command>
  setTNTRunLobby:
    description: sets the location of the lobby
    command: /<command>